# Generated by Django 5.0 on 2024-01-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdlbook',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
    ]
