# Generated by Django 5.0 on 2024-01-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_comment_is_active_comment_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='publish',
            new_name='recommend',
        ),
    ]
